base_url = "https://timschubert.net"
title = "Tim Schubert"
description = "Personal Webpage"
default_lang = "en"
compile_sass = true
highlight_code = true
highlight_theme = "ir-white"
generate_rss = true
rss_limit = 20
build_search_index = true
taxonomies = [
  {name = "tags"},
]
check_external_links = false

[extra]
author = { github = "https://github.com/timschubert", mail = "mail@timschubert.net", pgp = "mail@timschubert.net.asc", name = "Tim Schubert"}
